trigger:
- main
   
pool: test-bayard   

variables:
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'pricing-common-non-prod-pricing'
    repository: 'sk7n5cgh18wl37zmhrva56xfw2mncp/teste'
    command: 'buildAndPush'
    Dockerfile: 'app/Dockerfile'
    tags: |
      test1